//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCgparule
    {
        public int cgpa_rules_id { get; set; }
        public int minimum_marks { get; set; }
        public int maximum_marks { get; set; }
        public decimal grade_point { get; set; }
        public string letter_grade { get; set; }
        public string division_or_class { get; set; }
    }
}
