//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMarksheet
    {
        public int marksheet_id { get; set; }
        public int student_profile_id { get; set; }
        public string fathers_name { get; set; }
        public string mothers_name { get; set; }
        public string degree_name { get; set; }
        public string department_name { get; set; }
        public string semester_name { get; set; }
        public int roll_no { get; set; }
        public int reg_no { get; set; }
        public decimal grade_point { get; set; }
        public string letter_grade { get; set; }
    
        public virtual tblStudentProfile tblStudentProfile { get; set; }
    }
}
