//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineResultManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblSemester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSemester()
        {
            this.tblStudentProfiles = new HashSet<tblStudentProfile>();
        }
    
        public int semester_id { get; set; }
        [Display(Name = "Semester")]
        public string semester_name { get; set; }
        [Display(Name = "Degree")]
        public int degree_id { get; set; }
        [Display(Name = "Department")]
        public int department_id { get; set; }
    
        public virtual tblDegree tblDegree { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentProfile> tblStudentProfiles { get; set; }
    }
}
